### ISSUE TITLE
[Suggestion] Take a course in writing commit names

### ISSUE THREAD

**Issue by cohaereo** [AlekEagleYT/EagleBot-Eris#2]
what in the deepest darkest pit of hell are these commit names!?
![image](https://user-images.githubusercontent.com/25546261/54455842-a5714680-4754-11e9-95a6-712ea9479c95.png)

**Comment by AlekEagle** [comment]
I mean I could just push the letter x like my friend does

**Comment by WaviestBalloon** [comment]
x

**Comment by noob2332** [comment]
hey

**Comment by noob2332** [comment]
wtff

**Comment by noob2332** [comment]
help me

**Comment by WaviestBalloon** [comment]
> help me

If you need help, just create a new issue.

**Comment by noob2332** [comment]
.-.

**Comment by noob2332** [comment]
https://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdk

**Comment by noob2332** [comment]
https://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdk

**Comment by noob2332** [comment]
https://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdkhttps://www.youtube.com/watch?v=Kxx8l70-jdk

**Comment by noob2332** [comment]
https://www.youtube.com/watch?v=Kxx8l70-jdk

**Comment by noob2332** [comment]
https://www.youtube.com/watch?v=Kxx8l70-jdk

**Comment by noob2332** [comment]
https://www.youtube.com/watch?v=Kxx8l70-jdk

**Comment by WaviestBalloon** [comment]
> 
> 
> https://www.youtube.com/watch?v=Kxx8l70-jdk

Please stfu
